feat: adding validation to the branch name

diff --git a/.github/workflows/validate-branch-name.yml b/.github/workflows/validate-branch-name.yml
--- a/.github/workflows/validate-branch-name.yml
+++ b/.github/workflows/validate-branch-name.yml
@@ -4,9 +4,9 @@ on:
   push:
     branches:
       - '**'
-  pull_request:
-    branches:
-      - '**'
+  # pull_request:
+  #   branches:
+  #     - '**'
 
 jobs:
   validate-branch-name:
@@ -15,4 +15,13 @@ jobs:
       - name: Validate branch name
         run: |
           BRANCH_NAME="${GITHUB_REF#refs/heads/}"
+
           echo "Branch name: $BRANCH_NAME"
+
+          if [[ ! "$BRANCH_NAME" =~ ^(feat|fix|refactor|style|docs)\/[a-z0-9-]+$ ]]; then
+            echo "Branch name is invalid"
+            echo "It must follow the pattern: feat|fix|refactor|style|docs/<lowercase-description-with-dashes>"
+            exit 1
+          fi
+
+          echo "Branch name is valid!"
